use_frameworks!

target 'StachkaIOS' do
    # Animators
    pod 'RectangleDissolve', '~> 0.1.1'

    # Reactive extensions
    pod 'SDWebImage', '~>3.8'
    pod 'Kanna', '~> 2.1.0'
    pod 'RxSwift', '~> 3.3.0'
    pod 'RxCocoa', '~> 3.0'
    pod 'RxRealm'
    pod 'ObjectMapper', '~> 2.2'
    pod 'RxDataSources', '~> 1.0'
    pod 'ObjectMapper+Realm'
end
